### ISSUE TITLE
Governance Executable Functions

### ISSUE THREAD

**Issue by drikssy** [Debond-Protocol/Debond-Governance#8]

**Comment by drikssy** [comment]
We need to create all the functions that proposals would be able to execute... it can be a dedicated contract being inherited by the Governance contract
all these functions are accessible by proposal execution only (check https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/governance/Governor.sol#L289)

**Comment by Edoumou** [comment]
> We need to create all the functions that proposals would be able to execute... it can be a dedicated contract being inherited by the Governance contract all these functions are accessible by proposal execution only (check https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/governance/Governor.sol#L289)

Good @drikssy
